"""
PDF 报告生成模块。

使用 fpdf2 生成正式报告 PDF。
支持中文字体（自动探测 Windows/Mac/Linux 系统字体）。
"""

import base64
import os
from datetime import datetime
from io import BytesIO
from pathlib import Path

import pandas as pd
from fpdf import FPDF

# 自动探测系统可用的中文字体
# 优先 TTF 格式（兼容性更好），其次 TTC
_CJK_FONT_PATHS = [
    # Windows TTF
    "C:/Windows/Fonts/simhei.ttf",
    "C:/Windows/Fonts/deng.ttf",
    # Windows TTC
    "C:/Windows/Fonts/msyh.ttc",
    # macOS
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/STHeiti Light.ttc",
    # Linux (apt install fonts-noto-cjk)
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
    # Linux (apt install fonts-wqy-microhei)
    "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
    "/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf",
]
_CJK_FONT = None
for _p in _CJK_FONT_PATHS:
    if os.path.exists(_p):
        _CJK_FONT = _p
        break


def _add_cjk_font(pdf: FPDF, font_path: str) -> bool:
    """注册中文字体到 PDF，自动判断 TTC/TTF。"""
    try:
        is_ttc = font_path.lower().endswith(".ttc")
        # fpdf2 指定 ttc_index=0 以保证 TTC 使用第一个字体
        pdf.add_font("CJK", "", font_path, ttc_index=0) if is_ttc else pdf.add_font("CJK", "", font_path)
        # 加粗版本
        bold_path = font_path.replace(".ttc", "bd.ttc").replace(".ttf", "bd.ttf")
        if os.path.exists(bold_path):
            pdf.add_font("CJK", "B", bold_path, ttc_index=0) if is_ttc else pdf.add_font("CJK", "B", bold_path)
        else:
            pdf.add_font("CJK", "B", font_path, ttc_index=0) if is_ttc else pdf.add_font("CJK", "B", font_path)
        return True
    except Exception:
        return False


class _ReportPDF(FPDF):
    """自定义 PDF 样式（支持中文）。"""

    def __init__(self, watermark: str | None = None):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=18)
        self._use_cjk = _CJK_FONT is not None and _add_cjk_font(self, _CJK_FONT)
        self._watermark = watermark

    def _font(self, style="", size=10):
        """返回可用字体名（CJK 不支持 italic 时降级为常规）。"""
        if not self._use_cjk:
            return ("Helvetica", style, size)
        safe_style = style if style in ("", "B") else ""
        return ("CJK", safe_style, size)

    def header(self):
        if self.page_no() > 1:
            f = self._font("I", 8); self.set_font(*f)
            self.set_text_color(150, 150, 150)
            self.cell(0, 6, "Materials ML Diagnostic Report" if not self._use_cjk else "材料机器学习诊断报告", align="L")
            self.cell(0, 6, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.line(10, 14, 200, 14)
            self.ln(4)

    def footer(self):
        self.set_y(-15)
        f = self._font("", 7); self.set_font(*f)
        self.set_text_color(180, 180, 180)
        text = self._watermark or (
            "本报告由材料机器学习自动诊断工具生成，仅供参考"
            if self._use_cjk else "Generated by Materials ML Diagnostic Tool"
        )
        self.cell(0, 10, text, align="C")

    def section_title(self, title_cn: str, title_en: str = ""):
        title = title_en if not self._use_cjk else title_cn
        f = self._font("B", 13); self.set_font(*f)
        self.set_text_color(31, 119, 180)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(31, 119, 180)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def body_text(self, text: str):
        f = self._font("", 10); self.set_font(*f)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def check_space(self, needed_mm: float):
        """如果剩余空间不足，换页。needed_mm 是预估需要的高度。"""
        if self.get_y() + needed_mm > self.h - self.b_margin:
            self.add_page()

    def key_value(self, key_cn: str, value: str, key_en: str = ""):
        key = key_en if not self._use_cjk else key_cn
        f = self._font("", 10); self.set_font(*f)
        self.set_text_color(50, 50, 50)
        self.cell(60, 7, key, align="R")
        f = self._font("B", 10); self.set_font(*f)
        self.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def metric_grid(self, metrics: list[tuple[str, str, str]]):
        """三列指标卡片。"""
        x_start = self.get_x()
        y_start = self.get_y()
        self.set_fill_color(240, 244, 248)
        col_w = 57
        for i, (label, value, note) in enumerate(metrics):
            x = x_start + i * (col_w + 4)
            self.set_xy(x, y_start)
            self.rect(x, y_start, col_w, 22, style="DF")
            self.set_xy(x + 2, y_start + 2)
            f = self._font("B", 14); self.set_font(*f)
            self.set_text_color(31, 119, 180)
            self.cell(col_w - 4, 7, value)
            self.set_xy(x + 2, y_start + 10)
            f = self._font("", 8); self.set_font(*f)
            self.set_text_color(100, 100, 100)
            self.cell(col_w - 4, 5, label)
            if note:
                self.set_xy(x + 2, y_start + 15)
                f = self._font("", 7); self.set_font(*f)
                self.set_text_color(150, 150, 150)
                self.cell(col_w - 4, 4, note)
        self.set_xy(x_start, y_start + 26)


def _level_label(level: str, use_cjk: bool = True) -> str:
    labels_cn = {"A": "适合建模", "B": "可探索", "C": "高风险", "D": "不建议"}
    labels_en = {"A": "Adequate", "B": "Explorable", "C": "High Risk", "D": "Not Recommended"}
    return labels_cn.get(level, "—") if use_cjk else labels_en.get(level, "—")


def _next_steps_suggestions(diagnosis: dict | None, test_r2: float, sample_size: int, use_cjk: bool = True) -> list[str]:
    if not diagnosis:
        return []
    level = diagnosis["level"]
    if use_cjk:
        steps_map = {
            "A": [
                "优先关注 SHAP 重要性排名前 3 的特征，围绕这些变量设计验证实验",
                "检查特征之间的物理/化学关联性，确认模型识别的关系是否合理",
                "如目标 R² 满足要求，可进入论文建模阶段，建议补充外部验证集",
            ],
            "B": [
                "特征数/样本比偏低，建议补充 30%–50% 的样本量",
                "检查是否有高相关特征群，可合并或保留其中一个",
                "考虑增加与目标变量物理相关的特征，减少无关或噪声特征",
                "检查异常值来源，确认是测量误差还是真实极端条件",
            ],
            "C": [
                "当前模型不稳定，不建议用于正式分析",
                "优先排查数据质量问题：异常值、近重复、缺失模式",
                "检查目标变量分布是否存在极端偏态，考虑对数变换",
                "建议大幅扩充样本量（当前数据量下模型不可靠）",
                "如有可能，寻找文献中同类材料的已知特征-性能关系作为先验",
            ],
            "D": [
                "当前数据不适合机器学习建模",
                "建议重新评估数据采集方案：增加样本量、控制变量、降低测量误差",
                "检查目标变量的变异范围是否足够大（过小的变异无法建模）",
                "考虑是否用了正确的目标变量（数值型 vs 类别型）",
            ],
        }
    else:
        steps_map = {
            "A": [
                "Focus on top 3 SHAP features for validation experiments",
                "Check physical/chemical relevance of identified features",
                "Consider adding external validation set for publication",
            ],
            "B": [
                "Consider adding 30-50% more samples",
                "Check for highly correlated feature groups",
                "Add physically relevant features, reduce noise features",
                "Inspect outlier sources (measurement error vs extreme conditions)",
            ],
            "C": [
                "Model unstable — not recommended for formal analysis",
                "Prioritize data quality: outliers, near-duplicates, missing patterns",
                "Check target distribution skew, consider log transform",
                "Substantially increase sample size recommended",
                "Search literature for known feature-property relationships as prior",
            ],
            "D": [
                "Current data not suitable for ML modeling",
                "Reconsider data collection: more samples, controlled variables",
                "Check if target variable has sufficient variance",
                "Verify target variable type (numeric vs categorical)",
            ],
        }
    return steps_map.get(level, [])


def generate_pdf_report(
    original_shape: tuple,
    sample_size: int,
    feature_count: int,
    target_column: str,
    best_model_name: str,
    test_r2: float,
    train_r2: float,
    cv_r2_mean: float,
    cv_r2_std: float,
    mae: float,
    rmse: float,
    suggestions: list[str],
    diagnosis: dict | None = None,
    data_quality: dict | None = None,
    watermark: str | None = None,
    metrics_df: pd.DataFrame | None = None,
    hpo_results: dict | None = None,
    all_params_by_model: dict | None = None,
    scatter_plot_base64: str | None = None,
    convergence_plot_base64: str | None = None,
    generated_date: str | None = None,
) -> bytes:
    """
    生成 PDF 格式诊断报告。

    Args: 参数含义与 generate_report_text 一致。

    Returns:
        bytes: PDF 文件字节流
    """
    pdf = _ReportPDF(watermark=watermark)
    use_cjk = pdf._use_cjk
    _tr = lambda c, e: c if use_cjk else e
    pdf.add_page()

    # ========== 封面 ==========
    pdf.ln(20)
    f = pdf._font("B", 24); pdf.set_font(*f)
    pdf.set_text_color(31, 119, 180)
    pdf.cell(0, 15, _tr("材料机器学习诊断报告", "Materials ML Diagnostic Report"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    f = pdf._font("", 11); pdf.set_font(*f)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 7, _tr("生成时间：", "Generated: ") + (generated_date or datetime.now().strftime('%Y-%m-%d %H:%M')), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, _tr("目标列：", "Target: ") + target_column, align="C", new_x="LMARGIN", new_y="NEXT")
    if data_quality:
        pdf.cell(0, 7, _tr("数据集：", "Dataset: ") + data_quality.get('dataset', target_column), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(15)

    # ========== 诊断等级 ==========
    if diagnosis:
        level = diagnosis["level"]
        label = _level_label(level, use_cjk)
        colors = {"A": (26, 125, 54), "B": (184, 134, 11), "C": (204, 85, 0), "D": (179, 0, 0)}
        color = colors.get(level, (100, 100, 100))
        score = diagnosis["score"]

        pdf.set_fill_color(*color)
        pdf.set_text_color(255, 255, 255)
        f = pdf._font("B", 28); pdf.set_font(*f)
        pdf.cell(30, 30, f"  {level}  ", fill=True, align="C")
        f = pdf._font("", 12); pdf.set_font(*f)
        pdf.cell(0, 30, _tr(f"  {label}   评分 {score}/100", f"  {label}   Score {score}/100"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        f = pdf._font("I", 9); pdf.set_font(*f)
        pdf.set_text_color(80, 80, 80)
        reason = diagnosis.get("reason", "")
        if not use_cjk:
            # 英文降级：显示诊断等级摘要
            reason = f"Diagnosis: {level} ({label}) - Score {score}/100"
        pdf.multi_cell(0, 5, reason)
        pdf.ln(8)

    # ========== 数据概况 ==========
    pdf.section_title("数据概况", "Data Overview")
    pdf.key_value("原始样本数", str(original_shape[0]), "Original Rows")
    pdf.key_value(_tr("有效建模样本数", "Valid Samples"), str(sample_size))
    pdf.key_value(_tr("特征数量", "Features"), str(feature_count))
    pdf.key_value(_tr("目标列", "Target"), target_column)
    if data_quality:
        dq_parts = []
        if data_quality.get("duplicate_rows", 0) > 0:
            dq_parts.append(f"Duplicates: {data_quality['duplicate_rows']}" if not use_cjk else f"重复行：{data_quality['duplicate_rows']}")
        if data_quality.get("outlier_rows", 0) > 0:
            dq_parts.append(f"Outliers: {data_quality['outlier_rows']}" if not use_cjk else f"异常值行：{data_quality['outlier_rows']}")
        if data_quality.get("near_dup_rows", 0) > 0:
            dq_parts.append(f"Near-dups: {data_quality['near_dup_rows']}" if not use_cjk else f"近重复：{data_quality['near_dup_rows']}")
        if dq_parts:
            f = pdf._font("", 9); pdf.set_font(*f)
            pdf.set_text_color(180, 100, 0)
            prefix = "  Data Quality: " if not use_cjk else "  数据质量提示："
            pdf.cell(0, 7, prefix + " | ".join(dq_parts), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
    pdf.ln(4)

    # ========== 最佳模型 ==========
    pdf.section_title(_tr("最佳模型", "Best Model"), _tr("最佳模型", "Best Model"))
    f = pdf._font("B", 14); pdf.set_font(*f)
    pdf.set_text_color(31, 119, 180)
    pdf.cell(0, 10, best_model_name, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.metric_grid([
        (_tr("交叉验证 R2", "CV R2"), f"{cv_r2_mean:.4f}", f"±{cv_r2_std:.4f}"),
        (_tr("训练集 R2", "Train R2"), f"{train_r2:.4f}", ""),
        (_tr("测试集 R2", "Test R2"), f"{test_r2:.4f}", ""),
    ])
    pdf.metric_grid([
        ("MAE", f"{mae:.4f}", ""),
        ("RMSE", f"{rmse:.4f}", ""),
        ("", "", ""),
    ])
    pdf.ln(4)

    # ========== 模型对比表格 ==========
    if metrics_df is not None and len(metrics_df) > 1:
        pdf.check_space(60)
        pdf.section_title(_tr("模型对比", "Model Comparison"), _tr("模型对比", "Model Comparison"))
        # 表头
        headers = [_tr("模型", "Model"), "Train R²", "Test R²", "CV R²", "MAE", "RMSE"]
        col_widths = [36, 28, 28, 32, 28, 28]  # total ~180
        f = pdf._font("B", 8); pdf.set_font(*f)
        pdf.set_fill_color(31, 119, 180)
        pdf.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            pdf.cell(col_widths[i], 7, h, border=1, fill=True, align="C")
        pdf.ln()
        # 数据行
        f_alt = pdf._font("", 8); pdf.set_font(*f_alt)
        pdf.set_text_color(50, 50, 50)
        for idx, (_, row) in enumerate(metrics_df.iterrows()):
            if idx % 2 == 1:
                pdf.set_fill_color(245, 248, 252)
                fill = True
            else:
                fill = False
            pdf.cell(col_widths[0], 6, str(row["model"]), border=1, align="C", fill=fill)
            pdf.cell(col_widths[1], 6, f"{row['train_r2']:.4f}", border=1, align="C", fill=fill)
            pdf.cell(col_widths[2], 6, f"{row['test_r2']:.4f}", border=1, align="C", fill=fill)
            pdf.cell(col_widths[3], 6, f"{row['cv_r2_mean']:.4f}±{row['cv_r2_std']:.4f}", border=1, align="C", fill=fill)
            pdf.cell(col_widths[4], 6, f"{row['mae']:.4f}", border=1, align="C", fill=fill)
            pdf.cell(col_widths[5], 6, f"{row['rmse']:.4f}", border=1, align="C", fill=fill)
            pdf.ln()
        pdf.ln(4)

    # ========== HPO 超参数优化 ==========
    if hpo_results:
        pdf.check_space(40)
        pdf.section_title(_tr("超参数优化 (HPO) 结果", "Hyperparameter Optimization"), _tr("超参数优化 (HPO) 结果", "HPO Results"))
        methods = {r["method"] for r in hpo_results.values()}
        method_str = ", ".join(m.upper() for m in methods)
        f = pdf._font("", 10); pdf.set_font(*f)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 7, _tr("优化方法: ", "Method: ") + method_str, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        for model_name, hpo_res in hpo_results.items():
            params_str = ", ".join(f"{k}={v}" for k, v in hpo_res["best_params"].items())
            f = pdf._font("B", 9); pdf.set_font(*f)
            pdf.set_text_color(31, 119, 180)
            pdf.cell(0, 6, model_name, new_x="LMARGIN", new_y="NEXT")
            f = pdf._font("", 8); pdf.set_font(*f)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(0, 5, _tr(
                f"  CV R² = {hpo_res['best_score']:.4f}, RMSE = {hpo_res.get('best_rmse', 0.0):.4f} ({hpo_res['n_trials']} 轮)",
                f"  CV R² = {hpo_res['best_score']:.4f}, RMSE = {hpo_res.get('best_rmse', 0.0):.4f} ({hpo_res['n_trials']} trials)",
            ), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(100, 100, 100)
            pdf.set_x(15)  # indent
            f = pdf._font("", 7); pdf.set_font(*f)
            pdf.multi_cell(0, 4, f"  {params_str}")
            if all_params_by_model and model_name in all_params_by_model:
                all_p = all_params_by_model[model_name]
                tuned_keys = set(hpo_res["best_params"].keys())
                other = {k: v for k, v in all_p.items() if k not in tuned_keys}
                if other:
                    other_str = ", ".join(f"{k}={v}" for k, v in other.items())
                    pdf.set_text_color(140, 140, 140)
                    pdf.set_x(18)
                    pdf.multi_cell(0, 4, _tr(f"其他(默认): {{{other_str}}}", f"(defaults): {{{other_str}}}"))
            pdf.ln(2)
        pdf.ln(2)

    # ========== 图表 ==========
    if scatter_plot_base64:
        try:
            pdf.check_space(85)
            scatter_bytes = base64.b64decode(scatter_plot_base64)
            scatter_buf = BytesIO(scatter_bytes)
            pdf.image(scatter_buf, x=35, w=130)
            pdf.ln(3)
        except Exception:
            pass
    if convergence_plot_base64:
        try:
            pdf.check_space(85)
            conv_bytes = base64.b64decode(convergence_plot_base64)
            conv_buf = BytesIO(conv_bytes)
            pdf.image(conv_buf, x=35, w=130)
            pdf.ln(3)
        except Exception:
            pass

    # ========== 诊断建议 ==========
    if suggestions:
        pdf.section_title(_tr("诊断建议", "Recommendations"), _tr("诊断建议", "Recommendations"))
        f = pdf._font("", 10); pdf.set_font(*f)
        pdf.set_text_color(50, 50, 50)
        if not use_cjk:
            pdf.multi_cell(0, 6, "See the full report for detailed recommendations.")
        else:
            for s in suggestions:
                pdf.cell(5, 6, "-")
                pdf.multi_cell(0, 6, s)
                pdf.ln(1)
        pdf.ln(2)

    # ========== 下一步建议 ==========
    next_steps = _next_steps_suggestions(diagnosis, test_r2, sample_size, use_cjk)
    if next_steps:
        pdf.section_title(_tr("下一步建议", "Next Steps"), _tr("下一步建议", "Next Steps"))
        f = pdf._font("", 10); pdf.set_font(*f)
        pdf.set_text_color(50, 50, 50)
        if use_cjk:
            for i, step in enumerate(next_steps, 1):
                pdf.cell(5, 6, f"{i}.")
                pdf.multi_cell(0, 6, step)
                pdf.ln(1)
        else:
            for step in next_steps:
                pdf.cell(5, 6, "-")
                pdf.multi_cell(0, 6, step)
                pdf.ln(1)
        pdf.ln(2)

    # ========== 免责声明 ==========
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    f = pdf._font("I", 8); pdf.set_font(*f)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(0, 4.5,
        _tr(
            "免责声明：本工具仅用于科研数据初步分析，不代表因果结论，不保证论文发表。所有结果均基于自动化模型流程生成，仅供参考。",
            "Disclaimer: This tool is for preliminary data analysis only. Results are automated and do not represent causal conclusions or publication guarantees.",
        )
    )

    return bytes(pdf.output())
